@startuml

title __SRC's Class Diagram__\n

  namespace Bishop {
    class Bishop {
        + Bishop()
        + canMoveTo()
        + getType()
    }
  }
  

  namespace Chess {
    class Chess {
        ~ currentTurnColor : int
        ~ display : ChessDisplay
        ~ moveCount : int
        ~ piece : ChessPiece
        ~ pieceHasMoved : boolean
        + init()
        + mousePressed()
        + movePiece()
        + run()
    }
  }
  

  namespace ChessBoard {
    class ChessBoard {
        {static} + BOARD_SIZE : int
        - board : ChessPiece[][]
        + ChessBoard()
        + addPiece()
        + pieceAt()
        + removePiece()
        - isValidPosition()
    }
  }
  

  namespace King {
    class King {
        + King()
        + canMoveTo()
        + getType()
    }
  }
  

  namespace Knight {
    class Knight {
        + Knight()
        + canMoveTo()
        + getType()
    }
  }
  

  namespace Pawn {
    class Pawn {
        ~ hasMoved : boolean
        + Pawn()
        + canMoveTo()
        + getType()
    }
  }
  

  namespace PieceType {
    enum PieceType {
      BISHOP
      KING
      KNIGHT
      PAWN
      QUEEN
      ROOK
    }
  }
  

  namespace Queen {
    class Queen {
        + Queen()
        + canMoveTo()
        + getType()
    }
  }
  

  namespace Rook {
    class Rook {
        + Rook()
        + canMoveTo()
        + getType()
    }
  }
  

  Bishop -up-|> ChessPiece
  Chess .up.|> java.awt.event.MouseListener
  Chess -up-|> GraphicsProgram
  Chess o-- ChessBoard : board
  ChessBoard -up-|> DrawableObject
  King -up-|> ChessPiece
  Knight -up-|> ChessPiece
  Pawn -up-|> ChessPiece
  Queen -up-|> ChessPiece
  Rook -up-|> ChessPiece


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
